apiVersion: v1
kind: Service
metadata:
    name: {{.Values.serviceName}}
    namespace: {{ .Values.namespace }}
spec:
    type: ClusterIP
    ports:
    - port: 80
      name: http
      targetPort: 5005
    - port: 443
      name: https
      targetPort: 443
    selector:
      app: {{ .Values.serviceName}}
