apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: beunik-blog-api-app-keys
  namespace: production
spec:
  vault:
    name: azkv-beunik-production # name of key vault
    object:
      name: beunik-blog-api-app-keys # name of the akv object
      type: secret # akv object type
  output:
    secret:
      name: beunik-blog-api-app-keys # kubernetes secret name
      dataKey: app-keys
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: beunik-blog-api-token-salt
  namespace: production
spec:
  vault:
    name: azkv-beunik-production # name of key vault
    object:
      name: beunik-blog-api-token-salt # name of the akv object
      type: secret # akv object type
  output:
    secret:
      name: beunik-blog-api-token-salt # kubernetes secret name
      dataKey: token-salt
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: beunik-blog-api-admin-jwt-secret
  namespace: production
spec:
  vault:
    name: azkv-beunik-production # name of key vault
    object:
      name: beunik-blog-api-admin-jwt-secret # name of the akv object
      type: secret # akv object type
  output:
    secret:
      name: beunik-blog-api-admin-jwt-secret # kubernetes secret name
      dataKey: admin-jwt-secret
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: beunik-blog-api-transfer-token-salt
  namespace: production
spec:
  vault:
    name: azkv-beunik-production # name of key vault
    object:
      name: beunik-blog-api-transfer-token-salt # name of the akv object
      type: secret # akv object type
  output:
    secret:
      name: beunik-blog-api-transfer-token-salt # kubernetes secret name
      dataKey: transfer-token-salt
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: beunik-blog-api-jwt-secret
  namespace: production
spec:
  vault:
    name: azkv-beunik-production # name of key vault
    object:
      name: beunik-blog-api-jwt-secret # name of the akv object
      type: secret # akv object type
  output:
    secret:
      name: beunik-blog-api-jwt-secret # kubernetes secret name
      dataKey: jwt-secret
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: beunik-blog-api-bunny-api-key
  namespace: production
spec:
  vault:
    name: azkv-beunik-production # name of key vault
    object:
      name: beunik-blog-api-bunny-api-key # name of the akv object
      type: secret # akv object type
  output:
    secret:
      name: beunik-blog-api-bunny-api-key # kubernetes secret name
      dataKey: bunny-api-key
